name: Detection Workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  computer-vision-detection:
    name: Computer Vision Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run computer vision detection tests
        run: |
          pytest tests/computer_vision_detection.py

  change-detection:
    name: Change Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run change detection tests
        run: |
          pytest tests/change_detection.py

  anomaly-detection:
    name: Anomaly Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run anomaly detection tests
        run: |
          pytest tests/anomaly_detection.py

  non-computer-vision-detection:
    name: Non-Computer Vision Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run non-computer vision detection tests
        run: |
          pytest tests/non_computer_vision_detection.py

  data-detection:
    name: Dataset Involvement and Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run dataset detection tests
        run: |
          pytest tests/dataset_detection.py

  # Optional: Define matrix jobs to test on different Python versions or operating systems
  # matrix:
  #   python-version: [3.8, 3.9, 3.10]
  #   os: [ubuntu-latest, macos-latest, windows-latest]

  # Matrix jobs:
  #   - name: Test on ${{ matrix.python-version }}
  #     runs-on: ${{ matrix.os }}
  #     steps:
  #       - name: Checkout code
  #         uses: actions/checkout@v3
  #       - name: Set up Python
  #         uses: actions/setup-python@v4
  #         with:
  #           python-version: ${{ matrix.python-version }}
  #       - name: Install dependencies
  #         run: |
  #           pip install -r requirements.txt
  #       - name: Run tests
  #         run: |
  #           pytest tests
